config/routes.rb
BizPkns::Application.routes.draw do

  mount RedactorRails::Engine => '/redactor_rails'

  localized do
    get 'faq' => 'pages#faq', as: :faq
    get 'terms_and_conditions' => 'pages#terms_and_conditions', as: 'tnc'
    get "reports/users" => 'reports#users'
    get "reports/consultants" => 'reports#consultants'
    get "reports/programs" => 'reports#programs'
    get "reports/kpi" => 'reports#kpi'
    get "newsletters/history" => 'newsletters#history', as: "history"

    get "newsletters/new/:id" => 'newsletters#use_template', as: "use_template"
    get "home" => "pages#home"
    put 'make_member/:id' => 'users#make_member', as: :make_member
    match 'select_program/:program_id' => 'consultants#select_program', as: :select_program
    post 'update_attendance', to: 'members#update_attendance', as: 'update_attendance'
    get "newsletters/history" => 'newsletters#history', as: "history"
    get "newsletters/new/:id" => 'newsletters#use_template', as: "use_template"
    get "newsletters/preview/:id" => 'newsletters#preview', as: "preview_newsletter"
    get "letters/history" => 'letters#history', as: "letters_history"
    get "letters/list" => 'letters#list', as: "letters_list"
    get "letters/preview/:id" => 'letters#preview', as: "preview_letter"
    get "email/:id" => 'email#show', as: "show_email"
    match 'consultation' => "pages#consultation", as: :consultation
    match 'my_courses' => "pages#my_courses", as: :user_course_listing
    match 'program_users' => "members#program_member_list", as: :program_user_listing
    match "contact" => "pages#contact", as: :contact
    match 'create_message' => 'messages#create', as: :create_message
    get  '/upcoming_courses' => 'pages#upcoming_courses', as: :course_listing
    get 'blogs/tag/:tag', to: 'blogs#all', as: :tag
    match 'blog', to: 'blogs#all', as: :category_blog
    get 'blog/:id', to: 'blogs#show', as: :show_blog
    scope '/upcoming_courses' do 
       match '/:id' => 'pages#upcoming_courses_show', as: :course_details
       match '/:id/user/:user_id' => 'pages#register_user', as: :user_course_registration
    end

    match "/delayed_job" => DelayedJobWeb, :anchor => false
    match 'business_directory' => 'pages#business_directory', as: :business_directory
    get 'city_dropdown' => 'application#city_dropdown', as: :city_dropdown
    get 'course_dropdown' => 'application#course_dropdown', as: :course_dropdown
    devise_for :users, path_names: {sign_in: "login", sign_out: "logout", sign_up: "signup"},
                        controllers: {registrations: 'registrations', confirmations: 'confirmations', sessions: 'sessions'}
    devise_for :consultants, path_names: {sign_in: "login",  sign_out: "logout"}
    devise_scope :user do
      get "/admin/login" => "sessions#new_admin"
      post "/user/sign_in" => "sessions#create"
    end
    
    resources :reports, only: [] do
      collection do
        match 'users' => 'reports#users', as: :user
        match "consultants" => 'reports#consultants', as: :consultant
        match "programs" => 'reports#programs', as: :program
      end
    end
    resources :admin
    resources :adverts do
      member do 
        put 'activate' 
        put 'assign_weight'
        put 'make_request'
        post 'new'
        post 'edit'
      end
    end
    resources :consultants do
      member do
        match 'my_adverts', as: :my_adverts
        match 'my_reports', as: :my_reports
      end
    end
    resources :users do
      member do
        put 'update_membership' => 'users#update_membership'#, as: :update_membership
        get 'surveys'
        get 'letters', as: :letter_user
        match 'my_adverts', as: :my_adverts
      end 
      collection do
        get 'inactive' => 'users#inactive'
      end
    end
    resources :programs
    resources :courses do
      member do
        get 'generate_report'
        post 'create_report', as: :create_report
        get 'view_report'
        put 'update_report', as: :update_report
        get 'reports'
      end
      collection do 
        get 'list_reports'
      end
    end
    resources :members
    resources :educations
    resources :skills
    resources :blogs
    resources :attendance_list
    resources :pkns_users
    resources :businesses
    resources :email, :only => [:show]
    namespace :newsletters do resources :templates end
    resources :newsletters do
      member do
        post 'send_newsletter' => 'newsletters#send_newsletter', as: :send_user
      end
    end
    resources :past_attendances, except: [ :update, :destroy, :edit ] do
      collection do
        get 'uploaded'
      end
    end
    resources :business_categories
    resources :letters do
      collection do 
        get '' => 'letters#list'
      end
      member do
        post 'send_letter' => 'letters#send_letter', as: :send_user
        match 'generate_letter' => 'letters#generate_letter', as: :generate
      end
    end
    resources :surveys do
      member do
        post 'send_survey' => 'surveys#send_survey', as: :send_user
      end
      member do 
        get 'take'
        post 'take' => 'surveys#finish_survey'
        get 'report'
        post 'report'
      end
    end

    scope '/portal' do
      get '' => 'portals#home'
      get 'home' => 'portals#home', as: :portal_home
      get 'contact' => 'portals#contact', as: :portal_contact
      get 'course' => 'portals#course', as: :portal_course
      get 'faq' => 'portals#faq', as: :portal_faq
      get 'course/:id' => 'portals#course_show', as: :portal_course_show
      get 'members' => 'portals#member_page', as: :portal_members
    end
    get "pages/welcome", as: 'welcome_page'
    get "pages/adview", as: 'adview'
    get "consultants/:id/contact", :to => "consultants#contact", :as => 'contact_consultant'
    post "consultants/:id/contact/sent", :to => "consultants#sent", :as => 'contact_sent'
    get "letters/:id/compose", :to => "letters#compose", :as => 'compose_letter'
    put "admin/:id/update", :to => "admin#update", :as => "update_admin"

  end

  root :to => 'pages#welcome'

end

app/models/newsletter.rb
class Newsletter < ActiveRecord::Base
  attr_accessible :message, :subject, :consultant_id

  scope :latest, order('created_at DESC')

  belongs_to :consultant

  validates :subject, presence: true, on: :create
end

app/models/newsletters.rb
module Newsletters
  def self.table_name_prefix
    'newsletters_'
  end
end

app/models/newsletters/template.rb
class Newsletters::Template < ActiveRecord::Base
  attr_accessible :name, :template
end

app/controllers/newsletters/templates_controller.rb
class Newsletters::TemplatesController < ApplicationController
  # GET /newsletters/templates
  # GET /newsletters/templates.json
  def index
    @newsletters_templates = Newsletters::Template.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @newsletters_templates }
    end
  end

  # GET /newsletters/templates/1
  # GET /newsletters/templates/1.json
  def show
    @newsletters_template = Newsletters::Template.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @newsletters_template }
    end
  end

  # GET /newsletters/templates/new
  # GET /newsletters/templates/new.json
  def new
    @newsletters_template = Newsletters::Template.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @newsletters_template }
    end
  end

  # GET /newsletters/templates/1/edit
  def edit
    @newsletters_template = Newsletters::Template.find(params[:id])
  end

  # POST /newsletters/templates
  # POST /newsletters/templates.json
  def create
    @newsletters_template = Newsletters::Template.new(params[:newsletters_template])

    respond_to do |format|
      if @newsletters_template.save
        format.html { redirect_to @newsletters_template, notice: 'Template was successfully created.' }
        format.json { render json: @newsletters_template, status: :created, location: @newsletters_template }
      else
        format.html { render action: "new" }
        format.json { render json: @newsletters_template.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /newsletters/templates/1
  # PUT /newsletters/templates/1.json
  def update
    @newsletters_template = Newsletters::Template.find(params[:id])

    respond_to do |format|
      if @newsletters_template.update_attributes(params[:newsletters_template])
        format.html { redirect_to @newsletters_template, notice: 'Template was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @newsletters_template.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /newsletters/templates/1
  # DELETE /newsletters/templates/1.json
  def destroy
    @newsletters_template = Newsletters::Template.find(params[:id])
    @newsletters_template.destroy

    respond_to do |format|
      format.html { redirect_to newsletters_templates_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/newsletters_controller.rb
class NewslettersController < ApplicationController
  # GET /newsletters
  # GET /newsletters.json
  def index
    if current_consultant
      @newsletters = current_consultant.newsletters.latest
    else
      @newsletters = Newsletter.latest
    end
    @newsletters_templates = Newsletters::Template.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @newsletters }
    end
  end

  # GET /newsletters/1
  # GET /newsletters/1.json
  def show
    @newsletter = Newsletter.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @newsletter }
    end
  end

  # GET /newsletters/new
  # GET /newsletters/new.json
  def new


    @newsletter = Newsletter.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @newsletter }
    end
  end

  # GET /newsletters/1/edit
  def edit
    if current_consultant
      sign_in(:user, User.find_by_email('admin@admin.com'))
    end
    @newsletter = Newsletter.find(params[:id])
  end

  # POST /newsletters
  # POST /newsletters.json
  def create
    if current_consultant
      sign_out(:user)
    end

    @newsletter = Newsletter.new(params[:newsletter])
    @emailsubject = params[:newsletter][:subject]
    @emailmessage = params[:newsletter][:message]

    respond_to do |format|
      if @newsletter.save
        format.html { redirect_to preview_newsletter_path(@newsletter) }
        format.json { render json: @newsletter, status: :created, location: @newsletter }
      else
        flash[:notice] = "Subjek diperlukan"
        format.html { render action: "use_template" }
        format.json { render json: @newsletter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /newsletters/1
  # PUT /newsletters/1.json
  def update
    @newsletter = Newsletter.find(params[:id])

    respond_to do |format|
      if @newsletter.update_attributes(params[:newsletter])
        format.html { redirect_to preview_newsletter_path(@newsletter), notice: 'Buletin berjaya dikemas kini.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit", locals:{  newsletter: @newsletter }}
        format.json { render json: @newsletter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /newsletters/1
  # DELETE /newsletters/1.json
  def destroy
    @newsletter = Newsletter.find(params[:id])
    @newsletter.destroy

    respond_to do |format|
      format.html { redirect_to newsletters_url }
      format.json { head :no_content }
    end
  end

  def history
    
    if current_consultant
      @newsletters = current_consultant.newsletters.latest
    else
      @newsletters = Newsletter.latest
    end
    #@newsletters_templates = Newsletters::Template.all

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  def send_newsletter
     the_notice=t('successfully_sent_newsletter')
    users = []
    @newsletter = Newsletter.find(params[:id])
    if params[:newsletter_user_select].present?
      case params[:newsletter_user_select]
      when 'all_users'
        users = User.nonadmin
      when 'members'
        users = User.nonadmin.members
      when 'nonmembers'
        users = User.nonadmin.nonmembers
      when 'users_by_program'
        if params[:newsletter_program_select].present?
          the_program = Program.find(params[:newsletter_program_select])
          users = the_program.users
        end
      when 'users_by_course'
        if params[:newsletter_course_select].present?
          the_course = Course.find(params[:newsletter_course_select])
          users = the_course.users
        end
      else
        users = User.nonadmin
      end
    end
    if !users.empty?
      users.uniq.each do |user|
        NewsletterMailer.delay(:run_at => 3.minutes.from_now ).mailer_newsletter(user, @newsletter.subject, @newsletter.message)
        @newsletter.sent = true
        @newsletter.save
      end
    end
    respond_to do |format|
      format.html { redirect_to @newsletter, notice: the_notice }
    end
  end

  def use_template
    if current_consultant
      sign_in(:user, User.find_by_email('admin@admin.com'))
      #@newsletter = Newsletter.find(params[:id])
    end
    @newsletters_template = Newsletters::Template.find(params[:id])
    @newsletter = Newsletter.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @newsletter }
    end
  end

  def preview
    @newsletter = Newsletter.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @newsletter }
    end
  end
end

app/helpers/newsletters/templates_helper.rb
module Newsletters::TemplatesHelper
end

app/views/newsletters/_form.html.haml
- is_disabled = false
- is_disabled = @newsletter.sent? unless @newsletter.nil?
= form_for @newsletter, :html => { :class => 'form-horizontal' } do |f|
  %ul
    %li.field
      = f.label t('.subject')
      = f.text_field :subject, :class => 'text input', :placeholder => t('.subject'), disabled: is_disabled
    %li.field
      = f.label t('.message')
      = f.text_area :message, :class => 'textarea input redactor', disabled: is_disabled
      - if current_consultant
        = f.hidden_field :consultant_id, value: current_consultant.id
    
    - unless is_disabled 
      %li.field
        = f.label t('.send_to')

      %li.field
        %span.medium.pretty.btn.warning
          - if @newsletter.new_record?
            %button{:onClick => 'submit();'}=t('.create')
          - else
            %button{:onClick => 'submit();'}=t('.preview')
        %span.medium.pretty.btn.default
          = link_to t('cancel', :default => t("helpers.links.cancel")), newsletters_path

app/views/newsletters/edit.html.haml
- model_class = Newsletter
.row
  %h3.twelve.columns
    Edit Bulletin
  %hr.divider
.row
  .twelve.columns
    = render :partial => "form"

app/views/newsletters/history.html.haml
- model_class = Newsletter
.row
  %h3.eight.columns
    = t '.title'
  .four.columns.action
    %span.pretty.medium.primary.btn.entypo.icon-left.icon-list-add
      = link_to t('.new'), newsletters_path

.table
  .row.table-head
    .one.columns
      %h6.title= "Bil"
    .seven.columns
      %h6.title= t('.subject')
    .three.columns
      %h6.title= t('.created_at')
    .one.columns
      %h6.title= t('status')
  - @newsletters.each_with_index do |newsletter, i|
    .row.table-rows
      .one.columns
        %p
          = i + 1
      .seven.columns
        %p
          = link_to newsletter.subject, newsletter_path(newsletter), :class => 'name'
      .three.columns
        %p
          = newsletter.created_at.strftime("%d %b %y, %H:%M")
      .one.columns
        .row
          .twelve.columns
          .twelve.columns.hide
            %span.pretty.small.btn.info.icon-left.entypo.icon-list-add
              = link_to t('.edit', :default => t("helpers.links.edit")), edit_newsletter_path(newsletter)
          .twelve.columns
            %span.pretty.small.btn.info.icon-left.entypo.icon-eye
              = link_to t('.view'), newsletter_path(newsletter)
          .twelve.columns.hide
            %span.pretty.small.btn.info.icon-left.entypo.icon-trash
              = link_to t('.destroy', :default => t("helpers.links.destroy")), newsletter_path(newsletter),
                :method => :delete,
                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }

app/views/newsletters/index.html.haml
- model_class = Newsletter
.row
  %h3.ten.columns
    = t('.title', :default => model_class.model_name.human.pluralize)
  .two.columns.action.hide
    %span.pretty.medium.primary.btn.entypo.icon-left.icon-list-add
      = link_to t('new', :default => t("helpers.links.new")), new_newsletter_path
  %hr.divider
.row
  .twelve.columns
    - unless !@newsletters_template.nil?
      %table.table.table-striped
        %thead
          %tr
            %th= "Bil"
            %th= t('.name')
            %th
        %tbody
          - @newsletters_templates.each_with_index do |newsletters_template, i|
            %tr
              %td= i+1
              %td= newsletters_template.name
              %td
                %span.small.pretty.btn.warning
                  = link_to t('.use_this'), use_template_path(newsletters_template)
    - else
      %h5 Templates not available!

app/views/newsletters/new.html.haml
- model_class = Newsletter
.row
  %h3.twelve.columns
    = t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human
  %hr.divider
.row
  .twelve.columns
    = render :partial => "form"

app/views/newsletters/preview.html.haml
- model_class = Newsletter
.row
  %h3.twelve.columns
    = t('.title', :default => model_class.model_name.human)
  %hr
.row
  .twelve.columns
    %p
      = link_to "Klik untuk prebiu buletin", show_email_path(@newsletter)
.row
  .twelve.columns
    = form_for '', url: send_user_newsletter_path(id: @newsletter.id) do |f|
      %ul
        - if current_user
          - if current_user.admin?
            %li.field
              .picker
                = select_tag 'newsletter_user_select', options_for_select([[t('.all_users'),'all_users'],[t('.members'),'members'], [t('.nonmembers'),'nonmembers'],[t('.users_by_program'), 'users_by_program'],[t('.users_by_course'),'users_by_course']])
        - elsif current_consultant
          %li.field
            .picker
              = select_tag 'newsletter_user_select', options_for_select([[t('.users_by_program'), 'users_by_program'],[t('.users_by_course'),'users_by_course']])
        - if current_consultant
          %li.field
            .picker
              = select_tag 'newsletter_program_select', options_for_select(current_consultant.programs.all.map{|a| [a.name, a.id]}), disabled: false
          %li.field
            .picker
              = select_tag 'newsletter_course_select', options_for_select(Course.where(program_id: current_consultant.programs.first.id).map{ |a| [a.name,a.id]}), disabled: true, class: 'hide'
        - else
          %li.field
            .picker
              = select_tag 'newsletter_program_select', options_for_select(Program.all.map{|a| [a.name, a.id]}), disabled: true, class: 'hide'
          %li.field
            .picker
              = select_tag 'newsletter_course_select', options_for_select(Course.where(program_id: Program.first.id).map{ |a| [a.name,a.id]}), disabled: true, class: 'hide'
        %li.field
          %span.medium.pretty.btn.warning
            / = f.submit t('send')
            %button{:onClick => 'submit();'}=t('send')
          %span.medium.pretty.btn.warning
            = link_to t('edit', :default => t("helpers.links.edit")), edit_newsletter_path(@newsletter)
          %span.medium.pretty.btn.default
            = link_to t('cancel', :default => t("helpers.links.cancel")), newsletters_path

app/views/newsletters/show.html.haml
/ %style
/   html{ margin-top: 130px; }

- model_class = Newsletter
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= t('.subject') + ':'
  %br
  = @newsletter.subject
%p
  %strong= t('.message') + ':'
  %br
  = @newsletter.message.html_safe

- unless @newsletter.sent?
  .form-actions
    %span.medium.pretty.btn.secondary
      = link_to t('.edit', :default => t("helpers.links.edit")), edit_newsletter_path(@newsletter)
    %span.medium.pretty.btn.danger
      = link_to t('.destroy', :default => t("helpers.links.destroy")), newsletter_path(@newsletter), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }

app/views/newsletters/use_template.html.haml
- model_class = Newsletter
.row
  %h3.twelve.columns
    = t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human
  %small  
    = t('fill_all_fields_hint')
  %hr
.row
  .twelve.columns
    = form_for @newsletter, :html => { :class => 'form-horizontal' } do |f|
      %ul
        %li.field
          = f.label t('.subject')
          = f.text_field :subject, :class => 'text input input-xxlarge', :placeholder => t('.subject')
        %li.field
          = f.label t('.message')
          %small
            = "* Pastikan gambar dalam bentuk .jpg dan saiz dimension tidak melebihi 500x500"
          = f.text_area :message, :class => 'textarea redactor', :value => @newsletters_template.try(:template) || @newsletter.message
          - if current_consultant
            = f.hidden_field :consultant_id, value: current_consultant.id

        %li.field
          %span.medium.pretty.btn.warning
            / = f.submit t('.preview')
            %button{:onClick => 'submit();'}=t('.preview')
          %span.medium.pretty.btn.default
            = link_to t('cancel', :default => t("helpers.links.cancel")), newsletters_path