config/routes.rb
BizPkns::Application.routes.draw do

  mount RedactorRails::Engine => '/redactor_rails'

  localized do
    get 'faq' => 'pages#faq', as: :faq
    get 'terms_and_conditions' => 'pages#terms_and_conditions', as: 'tnc'
    get "reports/users" => 'reports#users'
    get "reports/consultants" => 'reports#consultants'
    get "reports/programs" => 'reports#programs'
    get "reports/kpi" => 'reports#kpi'
    get "newsletters/history" => 'newsletters#history', as: "history"

    get "newsletters/new/:id" => 'newsletters#use_template', as: "use_template"
    get "home" => "pages#home"
    put 'make_member/:id' => 'users#make_member', as: :make_member
    match 'select_program/:program_id' => 'consultants#select_program', as: :select_program
    post 'update_attendance', to: 'members#update_attendance', as: 'update_attendance'
    get "newsletters/history" => 'newsletters#history', as: "history"
    get "newsletters/new/:id" => 'newsletters#use_template', as: "use_template"
    get "newsletters/preview/:id" => 'newsletters#preview', as: "preview_newsletter"
    get "letters/history" => 'letters#history', as: "letters_history"
    get "letters/list" => 'letters#list', as: "letters_list"
    get "letters/preview/:id" => 'letters#preview', as: "preview_letter"
    get "email/:id" => 'email#show', as: "show_email"
    match 'consultation' => "pages#consultation", as: :consultation
    match 'my_courses' => "pages#my_courses", as: :user_course_listing
    match 'program_users' => "members#program_member_list", as: :program_user_listing
    match "contact" => "pages#contact", as: :contact
    match 'create_message' => 'messages#create', as: :create_message
    get  '/upcoming_courses' => 'pages#upcoming_courses', as: :course_listing
    get 'blogs/tag/:tag', to: 'blogs#all', as: :tag
    match 'blog', to: 'blogs#all', as: :category_blog
    get 'blog/:id', to: 'blogs#show', as: :show_blog
    scope '/upcoming_courses' do 
       match '/:id' => 'pages#upcoming_courses_show', as: :course_details
       match '/:id/user/:user_id' => 'pages#register_user', as: :user_course_registration
    end

    match "/delayed_job" => DelayedJobWeb, :anchor => false
    match 'business_directory' => 'pages#business_directory', as: :business_directory
    get 'city_dropdown' => 'application#city_dropdown', as: :city_dropdown
    get 'course_dropdown' => 'application#course_dropdown', as: :course_dropdown
    devise_for :users, path_names: {sign_in: "login", sign_out: "logout", sign_up: "signup"},
                        controllers: {registrations: 'registrations', confirmations: 'confirmations', sessions: 'sessions'}
    devise_for :consultants, path_names: {sign_in: "login",  sign_out: "logout"}
    devise_scope :user do
      get "/admin/login" => "sessions#new_admin"
      post "/user/sign_in" => "sessions#create"
    end
    
    resources :reports, only: [] do
      collection do
        match 'users' => 'reports#users', as: :user
        match "consultants" => 'reports#consultants', as: :consultant
        match "programs" => 'reports#programs', as: :program
      end
    end
    resources :admin
    resources :adverts do
      member do 
        put 'activate' 
        put 'assign_weight'
        put 'make_request'
        post 'new'
        post 'edit'
      end
    end
    resources :consultants do
      member do
        match 'my_adverts', as: :my_adverts
        match 'my_reports', as: :my_reports
      end
    end
    resources :users do
      member do
        put 'update_membership' => 'users#update_membership'#, as: :update_membership
        get 'surveys'
        get 'letters', as: :letter_user
        match 'my_adverts', as: :my_adverts
      end 
      collection do
        get 'inactive' => 'users#inactive'
      end
    end
    resources :programs
    resources :courses do
      member do
        get 'generate_report'
        post 'create_report', as: :create_report
        get 'view_report'
        put 'update_report', as: :update_report
        get 'reports'
      end
      collection do 
        get 'list_reports'
      end
    end
    resources :members
    resources :educations
    resources :skills
    resources :blogs
    resources :attendance_list
    resources :pkns_users
    resources :businesses
    resources :email, :only => [:show]
    namespace :newsletters do resources :templates end
    resources :newsletters do
      member do
        post 'send_newsletter' => 'newsletters#send_newsletter', as: :send_user
      end
    end
    resources :past_attendances, except: [ :update, :destroy, :edit ] do
      collection do
        get 'uploaded'
      end
    end
    resources :business_categories
    resources :letters do
      collection do 
        get '' => 'letters#list'
      end
      member do
        post 'send_letter' => 'letters#send_letter', as: :send_user
        match 'generate_letter' => 'letters#generate_letter', as: :generate
      end
    end
    resources :surveys do
      member do
        post 'send_survey' => 'surveys#send_survey', as: :send_user
      end
      member do 
        get 'take'
        post 'take' => 'surveys#finish_survey'
        get 'report'
        post 'report'
      end
    end

    scope '/portal' do
      get '' => 'portals#home'
      get 'home' => 'portals#home', as: :portal_home
      get 'contact' => 'portals#contact', as: :portal_contact
      get 'course' => 'portals#course', as: :portal_course
      get 'faq' => 'portals#faq', as: :portal_faq
      get 'course/:id' => 'portals#course_show', as: :portal_course_show
      get 'members' => 'portals#member_page', as: :portal_members
    end
    get "pages/welcome", as: 'welcome_page'
    get "pages/adview", as: 'adview'
    get "consultants/:id/contact", :to => "consultants#contact", :as => 'contact_consultant'
    post "consultants/:id/contact/sent", :to => "consultants#sent", :as => 'contact_sent'
    get "letters/:id/compose", :to => "letters#compose", :as => 'compose_letter'
    put "admin/:id/update", :to => "admin#update", :as => "update_admin"

  end

  root :to => 'pages#welcome'

end

app/models/letter.rb
class Letter < ActiveRecord::Base
  attr_accessible :user_id, :first_name, :last_name, :message, :subject
  attr_accessible :line1, :line2, :postcode, :city, :state
  attr_accessible :address

  validates :subject, presence: true
  has_many :users

  def full_name
    if self.first_name.blank?
      "#{self.last_name}"
    elsif self.last_name.blank?
      "#{self.first_name}"
    elsif self.first_name.blank? && self.last_name.blank?
      "NIL"
    else
      "#{self.first_name} #{self.last_name}"
    end
  end

  def full_address
    "#{self.line1} #{self.line2} #{self.postcode} #{self.city} #{self.state}"
  end

  def date
    created_at.strftime("%d %b %Y")
  end

  def sender_name(user)
    user.full_name
  end
end

app/controllers/letters_controller.rb
class LettersController < ApplicationController
  # GET /letters
  # GET /letters.json
  def index
    @letters = User.all
    if params[:search].present?
      if params[:search][:term].blank?
        
      else
        search_terms = params[:search][:term].split(' ').join('%')
        @letters = User.where("concat(LOWER(first_name), ' ', LOWER(last_name)) like ?","%#{search_terms}%")
      end
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @letters }
    end
  end

  # GET /letters/1
  # GET /letters/1.json
  def show
    @letter = Letter.find(params[:id])


    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @letter }
      format.pdf do
      #pdf = Prawn::Document.new
      pdf = LetterPdf.new(@letter, current_user)
      send_data pdf.render, filename: "surat_#{@letter.full_name}".downcase.gsub(' ', '_'),
                              type: "application/pdf",
                              disposition: "inline"
    end
    end
  end

  def generate_letter
    the_notice=t('successfully_sent_letter')
 
    @users = []
   
    @letter = Letter.find(params[:id])
    if params[:letter_user_select].present?
      case params[:letter_user_select]
      when 'all_users'
        @users = User.nonadmin.has_address
      when 'members'
        @users = User.nonadmin.members.has_address
      when 'nonmembers'
        @users = User.nonadmin.nonmembers.has_address
      when 'users_by_program'
        if params[:letter_program_select].present?
          the_program = Program.find(params[:letter_program_select])
          @users = the_program.users.has_address
        end
      when 'users_by_course'
        if params[:letter_course_select].present?
          the_course = Course.find(params[:letter_course_select])
          @users = the_course.users.has_address
        end
      else
        @users = User.nonadmin.has_address
      end
    end


    respond_to do |format|
      format.html { render 'generate_letter',layout: 'kpi_report' }# show.html.erb
      format.json { render json: @letter }
      format.pdf do
        #pdf = Prawn::Document.new
        pdf = LetterPdf.new(@letter, current_user, @users)
        send_data pdf.render, filename: "surat_#{@letter.subject}".downcase.gsub(' ', '_'),
                                type: "application/pdf",
                                disposition: "inline"
      end
    end
  end

  # GET /letters/new
  # GET /letters/new.json
  def new
    @letter = Letter.new(params[:letter])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @letter }
    end
  end

  # GET /letters/1/edit
  def edit
    #@user = User.find(params[:id])
    @letter = Letter.find(params[:id])
  end

  # POST /letters
  # POST /letters.json
  def create
    @letter = Letter.new(params[:letter])

    city_id = params[:user_city]

    respond_to do |format|
      if @letter.save
        format.html { redirect_to preview_letter_path(@letter), notice: 'Surat berjaya dicipta.' }
        format.json { render json: @letter, status: :created, location: @letter }
      else
        flash[:alert] = 'Perkara Diperlukan' 
        format.html { render 'new' }
        format.json { render json: @letter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /letters/1
  # PUT /letters/1.json
  def update
    @letter = Letter.find(params[:id])

    respond_to do |format|
      if @letter.update_attributes(params[:letter])
        format.html { redirect_to preview_letter_path(@letter), notice: 'Surat berjaya dikemas kini.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @letter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /letters/1
  # DELETE /letters/1.json
  def destroy
    @letter = Letter.find(params[:id])
    @letter.destroy

    respond_to do |format|
      format.html { redirect_to letters_url }
      format.json { head :no_content }
    end
  end

  def compose
    @user = User.find(params[:id])
    #@sender = current_user.email
    @letter = Letter.create(params[:letter])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @letter }
    end
  end

  def history
    @letters = Letter.order("created_at DESC").all

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  def send_letter
    the_notice=t('successfully_sent_letter')
    users = []
    @letter = Letter.find(params[:id])
    if params[:letter_user_select].present?
      case params[:letter_user_select]
      when 'all_users'
        users = User.nonadmin
      when 'members'
        users = User.nonadmin.members
      when 'nonmembers'
        users = User.nonadmin.nonmembers
      when 'users_by_program'
        if params[:letter_program_select].present?
          the_program = Program.find(params[:letter_program_select])
          users = the_program.users
        end
      when 'users_by_course'
        if params[:letter_course_select].present?
          the_course = Course.find(params[:letter_course_select])
          users = the_course.users
        end
      else
        users = User.nonadmin
      end
    end
    if !users.empty?
      users.uniq.each do |user|
      end
    end
    respond_to do |format|
      format.html { redirect_to generate_letter_path(@letter, users: users), notice: the_notice, users: users}
    end
  end

  def list
    @adverts = Advert.active
    @letters = Letter.order("created_at DESC")

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  def preview
    @letter = Letter.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @letter }
    end
  end
end

app/views/letters/_form.html.haml
= form_for @letter, :html => { :class => 'form-horizontal' } do |f|
  %ul
    %li.field
      .control-group
        = f.label t('.subject'), :class => 'control-label'
        .controls
          = f.text_field :subject, :class => 'text input input-xlarge', value: @letter.subject
      .control-group
        = f.label t('.message'), :class => 'control-label'
        .controls
          = f.text_area :message, :class => 'redactor-less',value: @letter.message, :rows => 40, :cols => 520
    %li.field
      %span.medium.pretty.btn.info
        - if @letter.new_record?
          - button_text = '.compose'
        - else
          - button_text = 'update'
        %button{:onClick => 'submit();'}=t button_text
      %span.medium.pretty.btn.danger
        = link_to t('.cancel', :default => t("helpers.links.cancel")), letters_path

app/views/letters/compose.html.haml
- model_class = Letter
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human

= form_for @letter, :html => { :class => 'form-horizontal' } do |f|
  
  %h4=t '.recipient'
  .control-group
    = f.label t('.name'), :class => 'control-label'
    .controls
      = f.text_field :first_name, :class => 'text_field', :value => @user.first_name
      = f.text_field :last_name, :class => 'text_field', :value => @user.last_name
      = f.text_field :user_id, :value => @user.id, type: "hidden"

  %h4=t '.address'
  .control-group
    = f.label t('.address'), :class => 'control-label'
    .controls
      = f.text_field :line1, :class => 'text_field', :placeholder => 'Baris 1', :value => @user.address.line1
  .control-group
    .controls
      = f.text_field :line2, :class => 'text_field', :placeholder => 'Baris 2', :value => @user.address.line2
  .control-group
    .controls
      = f.text_field :postcode, :class => 'text_field input-mini', :placeholder => 'Poskod', :value => @user.address.postcode
  .control-group
    = f.label t('.city'), :class => 'control-label'
    .controls
      = f.text_field :city, :class => 'text_field', :placeholder => 'Bandar', :value => @user.address.city.name
  .control-group
    = f.label t('.state'), :class => 'control-label'
    .controls
      = f.text_field :state, :class => 'text_field', :placeholder => 'Negeri', :value => @user.address.city.state_name

  %h4=t '.compose'
  .control-group
    = f.label t('.subject'), :class => 'control-label'
    .controls
      = f.text_field :subject, :class => 'text_field input-xlarge'
  .control-group
    = f.label t('.message'), :class => 'control-label'
    .controls
      = f.text_area :message, :class => 'redactor', :rows => 40, :cols => 520

  .form-actions
    %span.medium.pretty.btn.primary
      = f.submit t('.send')#, :class => 'btn btn-primary'
    %span.medium.pretty.btn.default
      = link_to t('.cancel', :default => t("helpers.links.cancel")), letters_path#, :class => 'btn'

app/views/letters/edit.html.haml
- model_class = Letter
.row
  %h3.twelve.columns
    = t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human
  %hr.divider
.row
  .twelve.columns
    = render :partial => "form"

app/views/letters/generate_letter.html.haml
- model_class = Letter
- @users.each_with_index do |user,index|
  - unless index == 0
    %h1.break
  .row
    %strong
      'KEJUJURAN DAN KETEKUNAN'
  .row
    .eight.columns
    .two.columns
      Surat Kami:
    .two.columns
  .row
    .eight.columns
    .two.columns
      Tarikh:
    .two.columns
      = @letter.date
  .row
    .twelve.columns
      .letter-format
        %p= user.full_name
        %p= full_address(user).html_safe
        .row
          %p
            Tuan/Puan,
        .row
          .twelve.columns
            %h5= "#{t('subject')} : #{@letter.subject}"
            %p
              =@letter.message.html_safe
        .row
          .twelve.columns
            %p
              Sekian, terima kasih.

            %strong.block
              "BERKHIDMAT UNTUK NEGARA"

            %p
              Saya yang menurut perintah
            %br
            %br
            %br
            %br
            %br
            %strong.block
              / = current_user.full_name
          %hr.divider
%h1.break
.row
  .twelve.columns
    %span.medium.pretty.btn.warning
      = link_to t('.print'), generate_letter_path(@letter, letter_user_select: params[:letter_user_select], letter_program_select: params[:letter_program_select], letter_course_select: params[:letter_course_select], format: "pdf"), method: :post
    %span.medium.pretty.btn.warning
      = link_to t('edit', :default => t("helpers.links.edit")), edit_letter_path(@letter)
    %span.medium.pretty.btn.danger
      = link_to t('destroy', :default => t("helpers.links.destroy")), letter_path(@letter), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }

app/views/letters/history.html.haml
- model_class = Letter
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= "Index"
      %th= t('.subject')
      %th= t('.name')
      %th= t('.created_at')
      %th
  %tbody
    - @letters.each_with_index do |letter, i|
      %tr
        %td= i+1
        %td= letter.subject
        %td= letter.full_name
        %td= letter.created_at.strftime("%d %b %y, %M:%S")
        %td
          %span.small.pretty.btn.primary
            = link_to t('.view'), letter_path(letter)

app/views/letters/index.html.haml
- model_class = Letter

.row
  %h3.ten.columns
    = t('.title', :default => model_class.model_name.human.pluralize)
  .two.columns.action
    %span.pretty.medium.primary.btn.entypo.icon-left.icon-list-add
      = link_to t('new', :default => t("helpers.links.new")), new_letter_path
.table
  .row.table-head
    .two.columns
      %h6.title= "Bil"
    .eight.columns
      %h6.title= t('.name')
    .two.columns
      %h6.title= t('status')
  - @letters.each_with_index do |letter, i|
    .row.table-rows
      .two.columns
        %p
          = link_to i + 1, letter_path(letter), :class => 'name'
      .eight.columns
        %p
          = "#{letter.first_name} #{letter.last_name}"
      .two.columns
        .row
          .twelve.columns
          .twelve.columns
            %span.pretty.small.btn.warning.icon-left.entypo.icon-mail
              = link_to t('.history'), letter_user_user_path(letter)
          .twelve.columns
            %span.pretty.small.btn.danger.icon-left.entypo.icon-pencil
              = link_to t('.send_letter'), compose_letter_path(letter)

app/views/letters/list.html.haml
- model_class = Letter
.row
  %h3.eight.columns
    = t('.title')
  .four.columns.action
    %span.pretty.medium.primary.btn.entypo.icon-left.icon-list-add
      = link_to t('.new'), new_letter_path
%table.table.table-striped
  %thead
    %tr
      %th= "Bil"
      %th= t('.subject')
      %th= t('.created_at')
      %th
  %tbody
    - @letters.each_with_index do |letter, i|
      %tr
        %td= i+1
        %td= letter.subject
        %td= letter.created_at.strftime("%d %b %y, %H:%M")
        %td
          %span.small.pretty.btn.primary
            = link_to t('.preview'), preview_letter_path(letter)

app/views/letters/new.html.haml
- model_class = Letter
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human
  %small
    = t('fill_all_fields_hint')
= render :partial => "form"

app/views/letters/preview.html.haml
- model_class = Letter
.row
  %h3.twelve.columns
    = t('.title', :default => model_class.model_name.human)
  %hr.divider
.row
  .twelve.columns
    %h5= t('.subject') + ':'
    %p
      =@letter.message.html_safe
  %hr.divider
.row
  .twelve.columns
    = form_for '', url: generate_letter_path(id: @letter.id) do |f|
      %ul
        - if current_user
          - if current_user.admin?
            %li.field
              .row
                .twelve.columns
                  .picker
                    = select_tag 'letter_user_select', options_for_select([[t('.all_users'),'all_users'],[t('.members'),'members'], [t('.nonmembers'),'nonmembers'],[t('.users_by_program'), 'users_by_program'],[t('.users_by_course'),'users_by_course']])
      
            %li.field
              .row
                .six.columns
                  .picker
                    = select_tag 'letter_program_select', options_for_select(Program.all.map{|a| [a.name, a.id]}), disabled: true
            %li.field
              .row
                .six.columns
                  .picker
                    = select_tag 'letter_course_select', options_for_select(Course.where(program_id: Program.first.id).map{ |a| [a.name,a.id]}), disabled: true
        %li.field
          %hr.divider
          %span.medium.pretty.btn.warning
            %button{:onClick => 'submit();'}= t('.print_pdf')
          %span.medium.pretty.btn.warning
            = link_to t('edit', :default => t("helpers.links.edit")), edit_letter_path(@letter)
          %span.medium.pretty.btn.danger
            = link_to t('back', :default => t("helpers.links.cancel")), letters_path

app/views/letters/show.html.haml
- model_class = Letter
.page-header
  %h1

= @letter.full_name
- if @letter.line2.blank?
  %br
  = @letter.line1
  %br
  = @letter.postcode
  %br
  = @letter.city 
  = @letter.state
- else
  %br
  = @letter.line1
  %br
  = @letter.line2
  %br
  = @letter.postcode
  %br
  = @letter.city 
  = @letter.state
  %br
%br
  = @letter.date
%p
  %br
  %strong= 'Subjek :'
  = @letter.subject
%p
  = @letter.message.html_safe

%p
  Yang bertugas,

%p
  = current_user.full_name

.form-actions
  %span.medium.pretty.btn.primary
    = link_to t('.print'), letter_path(@letter, format: "pdf")#, :class => 'btn btn-secondary'
  %span.medium.pretty.btn.secondary
    = link_to t('.edit', :default => t("helpers.links.edit")), edit_letter_path(@letter)#, :class => 'btn'
  %span.medium.pretty.btn.danger
    = link_to t('.destroy', :default => t("helpers.links.destroy")), letter_path(@letter), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }#, :class => 'btn btn-danger'