config/routes.rb
BizPkns::Application.routes.draw do

  mount RedactorRails::Engine => '/redactor_rails'

  localized do
    get 'faq' => 'pages#faq', as: :faq
    get 'terms_and_conditions' => 'pages#terms_and_conditions', as: 'tnc'
    get "reports/users" => 'reports#users'
    get "reports/consultants" => 'reports#consultants'
    get "reports/programs" => 'reports#programs'
    get "reports/kpi" => 'reports#kpi'
    get "newsletters/history" => 'newsletters#history', as: "history"

    get "newsletters/new/:id" => 'newsletters#use_template', as: "use_template"
    get "home" => "pages#home"
    put 'make_member/:id' => 'users#make_member', as: :make_member
    match 'select_program/:program_id' => 'consultants#select_program', as: :select_program
    post 'update_attendance', to: 'members#update_attendance', as: 'update_attendance'
    get "newsletters/history" => 'newsletters#history', as: "history"
    get "newsletters/new/:id" => 'newsletters#use_template', as: "use_template"
    get "newsletters/preview/:id" => 'newsletters#preview', as: "preview_newsletter"
    get "letters/history" => 'letters#history', as: "letters_history"
    get "letters/list" => 'letters#list', as: "letters_list"
    get "letters/preview/:id" => 'letters#preview', as: "preview_letter"
    get "email/:id" => 'email#show', as: "show_email"
    match 'consultation' => "pages#consultation", as: :consultation
    match 'my_courses' => "pages#my_courses", as: :user_course_listing
    match 'program_users' => "members#program_member_list", as: :program_user_listing
    match "contact" => "pages#contact", as: :contact
    match 'create_message' => 'messages#create', as: :create_message
    get  '/upcoming_courses' => 'pages#upcoming_courses', as: :course_listing
    get 'blogs/tag/:tag', to: 'blogs#all', as: :tag
    match 'blog', to: 'blogs#all', as: :category_blog
    get 'blog/:id', to: 'blogs#show', as: :show_blog
    scope '/upcoming_courses' do 
       match '/:id' => 'pages#upcoming_courses_show', as: :course_details
       match '/:id/user/:user_id' => 'pages#register_user', as: :user_course_registration
    end

    match "/delayed_job" => DelayedJobWeb, :anchor => false
    match 'business_directory' => 'pages#business_directory', as: :business_directory
    get 'city_dropdown' => 'application#city_dropdown', as: :city_dropdown
    get 'course_dropdown' => 'application#course_dropdown', as: :course_dropdown
    devise_for :users, path_names: {sign_in: "login", sign_out: "logout", sign_up: "signup"},
                        controllers: {registrations: 'registrations', confirmations: 'confirmations', sessions: 'sessions'}
    devise_for :consultants, path_names: {sign_in: "login",  sign_out: "logout"}
    devise_scope :user do
      get "/admin/login" => "sessions#new_admin"
      post "/user/sign_in" => "sessions#create"
    end
    
    resources :reports, only: [] do
      collection do
        match 'users' => 'reports#users', as: :user
        match "consultants" => 'reports#consultants', as: :consultant
        match "programs" => 'reports#programs', as: :program
      end
    end
    resources :admin
    resources :adverts do
      member do 
        put 'activate' 
        put 'assign_weight'
        put 'make_request'
        post 'new'
        post 'edit'
      end
    end
    resources :consultants do
      member do
        match 'my_adverts', as: :my_adverts
        match 'my_reports', as: :my_reports
      end
    end
    resources :users do
      member do
        put 'update_membership' => 'users#update_membership'#, as: :update_membership
        get 'surveys'
        get 'letters', as: :letter_user
        match 'my_adverts', as: :my_adverts
      end 
      collection do
        get 'inactive' => 'users#inactive'
      end
    end
    resources :programs
    resources :courses do
      member do
        get 'generate_report'
        post 'create_report', as: :create_report
        get 'view_report'
        put 'update_report', as: :update_report
        get 'reports'
      end
      collection do 
        get 'list_reports'
      end
    end
    resources :members
    resources :educations
    resources :skills
    resources :blogs
    resources :attendance_list
    resources :pkns_users
    resources :businesses
    resources :email, :only => [:show]
    namespace :newsletters do resources :templates end
    resources :newsletters do
      member do
        post 'send_newsletter' => 'newsletters#send_newsletter', as: :send_user
      end
    end
    resources :past_attendances, except: [ :update, :destroy, :edit ] do
      collection do
        get 'uploaded'
      end
    end
    resources :business_categories
    resources :letters do
      collection do 
        get '' => 'letters#list'
      end
      member do
        post 'send_letter' => 'letters#send_letter', as: :send_user
        match 'generate_letter' => 'letters#generate_letter', as: :generate
      end
    end
    resources :surveys do
      member do
        post 'send_survey' => 'surveys#send_survey', as: :send_user
      end
      member do 
        get 'take'
        post 'take' => 'surveys#finish_survey'
        get 'report'
        post 'report'
      end
    end

    scope '/portal' do
      get '' => 'portals#home'
      get 'home' => 'portals#home', as: :portal_home
      get 'contact' => 'portals#contact', as: :portal_contact
      get 'course' => 'portals#course', as: :portal_course
      get 'faq' => 'portals#faq', as: :portal_faq
      get 'course/:id' => 'portals#course_show', as: :portal_course_show
      get 'members' => 'portals#member_page', as: :portal_members
    end
    get "pages/welcome", as: 'welcome_page'
    get "pages/adview", as: 'adview'
    get "consultants/:id/contact", :to => "consultants#contact", :as => 'contact_consultant'
    post "consultants/:id/contact/sent", :to => "consultants#sent", :as => 'contact_sent'
    get "letters/:id/compose", :to => "letters#compose", :as => 'compose_letter'
    put "admin/:id/update", :to => "admin#update", :as => "update_admin"

  end

  root :to => 'pages#welcome'

end

app/models/survey.rb
class Survey < ActiveRecord::Base
  attr_accessible :title, :questions_attributes, :description, :completed, :start_date, :end_date

  validates :title, presence: true

  has_many :questions
  accepts_nested_attributes_for :questions
  has_many :completed_surveys
  has_many :users, through: :completed_surveys

  belongs_to :creator, class_name: User

  scope :active, where('start_date <= ? AND end_date > ?', Date.today, Date.today)
  scope :latest, order('created_at DESC')
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  load_and_authorize_resource
  def index
    @surveys = Survey.latest
  end

  def show
    @survey = Survey.find(params[:id])
  end

  def new
    @survey = Survey.new
  end

  def create
    @survey = Survey.new(params[:survey])
    respond_to do |format|
      if @survey.save

        format.html { redirect_to @survey, notice: t('successfully_created_survey') }

      else
        flash[:notice] = "Nama diperlukan"
        format.html { render 'new'}

      end

    end
  end

  def edit
    @survey = Survey.find(params[:id])
  end

  def update
    @survey = Survey.find(params[:id])

    if @survey.update_attributes(params[:survey])
      respond_to do |format|
        @survey.reload
        
        if @survey.completed?
          format.html {redirect_to surveys_path , notice: t('successfully_ended_survey') }
        else
          format.html { redirect_to survey_path(@survey), notice: t('successfully_updated_survey') }
        end
      end
    end
  end

  def destroy
    @survey = Survey.find(params[:id])
    @survey.destroy

    respond_to do |format|
      format.html { redirect_to request.referrer }
      format.json { head :no_content }
    end
  end

  def send_survey
    the_notice=t('successfully_sent_survey')
    users = []
    @survey = Survey.find(params[:id])
    if params[:survey_user_select].present?
      case params[:survey_user_select]
      when 'all_users'
        users = User.nonadmin
      when 'members'
        users = User.nonadmin.members
      when 'nonmembers'
        users = User.nonadmin.nonmembers
      when 'users_by_program'
        if params[:survey_program_select].present?
          the_program = Program.find(params[:survey_program_select])
          users = the_program.users
        end
      when 'users_by_course'
        if params[:survey_course_select].present?
          the_course = Course.find(params[:survey_course_select])
          users = the_course.users
        end
      else
        users = User.nonadmin
      end
    end
    if !users.empty?
      users.uniq.each do |user|
        @survey.users << user unless @survey.users.include?(user)
        UserMailer.mail_survey_invite(user, @survey).deliver
      end
      @survey.sent = true
    end
    respond_to do |format|
      if @survey.save
        format.html { redirect_to survey_path(@survey), notice: the_notice }
      else
        the_notice = 'something went wrong'
        format.html { redirect_to survey_path(@survey), notice: the_notice}
      end
    end
  end

  def take
    @survey = Survey.find(params[:id])
    @questions = @survey.questions
  end

  def finish_survey
    if params[:question].present?
      params[:question].each do |q|
        current_user.responses << Response.create(question_id: q[1][:question_id], answer: q[1][:answer])
      end
    end
    survey = Survey.find(params[:id])
    completed_survey = current_user.completed_surveys.where(survey_id: survey).first
    completed_survey.completed = true
    completed_survey.save
    respond_to do |format|
      if !current_user.unfinished_surveys.empty?
        format.html { redirect_to surveys_user_path(current_user), notice: t('thanks_for_completing_our_survey') }
      else
        format.html { redirect_to home_url, notice: t('thanks_for_completing_our_survey')}
      end
    end
  end


  def report
    @survey = Survey.find(params[:id])
  end
end

app/views/surveys/_form.html.haml
- if @survey.new_record?
  - the_path = surveys_path(@survey)
  - the_method = :post
- else
  - the_path = survey_path(@survey.id)
  - the_method = :put
= nested_form_for @survey, url: the_path, :html => { :class => 'form-horizontal' }, method: the_method do |f|
  .field
    = f.label t(".name"), :class => 'control-label'
    .controls
      = f.text_field :title, :class => 'text input', :placeholder => t('title')
  .field
    = f.label t('description'), class: 'control-label'
    = f.text_area :description, class: 'input textarea redactor', :rows => '7'
  .field
    .row
      .six.columns
        = f.text_field :start_date, :class => 'input type start_date datepicker', :include_blank => true, :placeholder => t('start_date'), id: 'start_date'
      .six.columns
        = f.text_field :end_date, :class => 'input type end_date datepicker', :include_blank => true, :placeholder => t('end_date'), id: 'end_date'
  .field.questions
    %h4
      = t('questions')
    = f.fields_for :questions do |q|
      - if q.object.new_record?
        - question_id = q.options[:child_index]
      - else
        - question_id = q.object.id
      .field
        = q.label t('questions'), class: 'control-label'
        = q.text_area :title, class: 'input textarea redactor', :rows => '4'
      .field
        = q.label t('question_type'), class: 'control-label'
        .picker
          = q.select :question_type, options_for_select([[t('yes_no'),'yes_no'],[t('multiple_choice'),'multiple_choice'],[t('scale'),'scale'], [t('subjective'),'subjective']], q.object.question_type), {},{ onchange: "change_question_type(this.value, #{question_id});", class: "question_#{question_id}" }
        %p.hide{ class: "scale_#{question_id}"}
          1 (Sangat Setuju) - 5 (Sangat Tidak Setuju)
      - if q.object.new_record?
        .question_options.hide{ class: "#{question_id}" }
          .field
            = q.label t('option1'), class: 'control-label'
            = q.text_field :option1, class: 'text input', :placeholder => ''
          .field
            = q.label t('option2'), class: 'control-label'
            = q.text_field :option2, class: 'text input', :placeholder => ''
          .field
            = q.label t('option3'), class: 'control-label'
            = q.text_field :option3, class: 'text input', :placeholder => ''
          .field
            = q.label t('option4'), class: 'control-label'
            = q.text_field :option4, class: 'text input', :placeholder => ''
      - else
        - if q.object.question_type == 'multiple_choice'
          .question_options{ class: "#{question_id}" }
            .field
              = q.label t('option1'), class: 'control-label'
              = q.text_field :option1, class: 'text input', :placeholder => ''
            .field
              = q.label t('option2'), class: 'control-label'
              = q.text_field :option2, class: 'text input', :placeholder => ''
            .field
              = q.label t('option3'), class: 'control-label'
              = q.text_field :option3, class: 'text input', :placeholder => ''
            .field
              = q.label t('option4'), class: 'control-label'
              = q.text_field :option4, class: 'text input', :placeholder => ''
        - else
          .question_options.hide{ class: "#{question_id}" }
            .field
              = q.label t('option1'), class: 'control-label'
              = q.text_field :option1, class: 'text input', :placeholder => ''
            .field
              = q.label t('option2'), class: 'control-label'
              = q.text_field :option2, class: 'text input', :placeholder => ''
            .field
              = q.label t('option3'), class: 'control-label'
              = q.text_field :option3, class: 'text input', :placeholder => ''
            .field
              = q.label t('option4'), class: 'control-label'
              = q.text_field :option4, class: 'text input', :placeholder => ''

        = q.link_to_remove t('remove')
    = f.link_to_add :questions, :class => 'add-question' do
      %i.icon-plus-circled
      = t('add_questions')
  .field
    %hr.divider
    - if f.object.new_record?
      %span.medium.pretty.btn.warning
        %button{:value => 'submit', :onClick => 'submit();'}
          =t('.create')
        / = f.submit t('.create')
    - else
      %span.medium.pretty.btn.warning
        %button{:value => 'submit', :onClick => 'submit();'}
          =t('update')
        / = f.submit t('update')

:javascript
  var change_question_type
  change_question_type = function(question, options_id) {
  if(question =='multiple_choice'){
  $('.' + options_id).show();
  $('.scale_'+ options_id).hide();
  }
  else if(question=='scale'){
  $('.scale_'+ options_id).show();
  $('.' + options_id).hide();
  }
  else{
  $('.' + options_id).hide();
  $('.scale_'+ options_id).hide();
  }
  };

app/views/surveys/_survey_graphs.html.erb
<script type="text/javascript">
  google.load("visualization", "1", {packages:["corechart"]});
  google.setOnLoadCallback(drawPieChart);
  function drawPieChart() {
        var data = google.visualization.arrayToDataTable(<%= graph_data.to_s.html_safe %>);

        var options = {
          title: <%= chart_title %>,
          width: '600',
          height: '400'
        };

        var chart = new google.visualization.<%= chart_type.capitalize %>Chart(document.getElementById('<%= div_name.to_s %>'));
        chart.draw(data, options);
   }

  
</script>

app/views/surveys/edit.html.haml
- model_class = Survey
.row
  %h3.twelve.columns
    = t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human
  %small
    = t('fill_all_fields_hint')
  %hr.divider
.row
  .twelve.columns
    = render :partial => "form"

app/views/surveys/index.html.haml
- model_class = Survey
.row
  %h3.ten.columns
    = t('.title', :default => model_class.model_name.human.pluralize)
  .two.columns.action
    %span.pretty.medium.primary.btn.entypo.icon-left.icon-list-add
      = link_to t('new', :default => t("helpers.links.new")), new_survey_path
.table
  .row.table-head
    .two.columns
      %h6.title= "Bil"
    .eight.columns
      %h6.title= t('name')
    .two.columns
      %h6.title= t('status')
  - @surveys.each_with_index do |survey, i|
    .row.table-rows
      .two.columns
        %p
          = "#{i+1}"
      .eight.columns
        %p
          = link_to "#{survey.title}", survey_path(survey), :class => 'name'
        - unless survey.description.blank?
          %p
            = sanitize(survey.description[0..140])
            - if survey.description.size > 140
              = '...'
        - else
          %p
            %em Huraian tidak dijumpai.
      .two.columns
        .row
          .twelve.columns
          .twelve.columns.hide
            %span.pretty.small.btn.warning.icon-left.entypo.icon-eye
              = link_to t('view'), survey_path(survey)
          - if can? :edit, survey
            .twelve.columns
              %span.pretty.small.btn.warning.icon-left.entypo.icon-list-add
                = link_to t('edit', :default => t("helpers.links.edit")), edit_survey_path(survey)
            .twelve.columns
              %span.pretty.small.btn.danger.icon-left.entypo.icon-trash
                = link_to t('destroy', :default => t("helpers.links.destroy")), survey_path(survey),
                  :method => :delete,
                  :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }

app/views/surveys/new.html.haml
- model_class = Survey
.row
  %h3.twelve.columns
    = t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human
  %small
    = t('fill_all_fields_hint')
  %hr.divider
.row
  .twelve.columns
    = render :partial => "form"

app/views/surveys/report.html.haml
.row
  %h3.twelve.columns
    ="Laporan " + @survey.title
    - chart_type = params[:chart][:type] rescue 'bar'
    - chart_type = 'column' if chart_type == 'bar'
  %hr.divider
.row
  .eight.columns
    %h5= t('.question_breakdown')
  .four.columns
    %span.label.info= "#{t('.answered')} : #{@survey.users.where('completed_surveys.completed is true').count}"
    %span.label.info= "#{t('.requested')} : #{@survey.users.count}"

%script{ :src => 'http://www.google.com/jsapi', :type => 'text/javascript', :charset => 'utf-8' }

.row
  .twelve.columns
    %section.vertical.tabs
      = form_for '' do
        %ul.tab-nav.four.columns
          %li
            = link_to '#' do
              = radio_button 'chart','type', 'bar', onClick: 'submit();',checked: ( chart_type == 'bar' ? 'checked' : false )
              = t('.bar_chart')
          %li
            = link_to '#' do
              = radio_button 'chart','type', 'pie', onClick: 'submit();',checked: ( chart_type == 'pie' ? 'checked' : false )
              = t('.pie_chart')
        .tab-content.eight.columns.active
          - @survey.questions.each_with_index do |q,index|
            
            %h6
              = t('.question') + " #{index + 1}"
            %strong
              = t('.question') + ": "
            = q.title
            - if q.question_type == 'multiple_choice'
              %br
              %ul
                %li
                  = "(A): " + ( q.option1.blank? ? '' : q.option1 )
                %li
                  = "(B): " + ( q.option2.blank? ? '' : q.option2 )
                %li
                  = "(C): " + ( q.option3.blank? ? '' : q.option3 )
                %li
                  = "(D): " + ( q.option4.blank? ? '' : q.option4 )
            - case q.question_type
              - when 'yes_no'
                %table.table.table-striped
                  %thead
                    %tr
                      %th
                        = t('yes_answer')
                      %th
                        = t('no_answer')
                  %tbody
                    %tr
                      %td
                        = q.responses.where('answer = ?','yes').count
                      %td
                        = q.responses.where('answer = ?','no').count
                
                  = render partial: 'survey_graphs', locals: { div_name: "chart_#{index}", graph_data: [['Jawapan','Bil'],['Yes',q.responses.where('answer = ?','yes').count],['No',q.responses.where('answer = ?','no').count]], chart_title: "'Soalan #{index + 1}'", chart_type: chart_type}
                  = content_tag('div','',id: "chart_#{index}")
              - when 'multiple_choice'
                %table.table.table-striped{ style: "width: 400px;"}
                  %thead
                    %tr
                      %th
                        A
                      %th
                        B
                      %th
                        C
                      %th
                        D
                  %tbody
                    %tr
                      %td
                        = q.responses.where('answer = ?','A').count
                      %td
                        = q.responses.where('answer = ?','B').count
                      %td
                        = q.responses.where('answer = ?','C').count
                      %td
                        = q.responses.where('answer = ?','D').count

                  = render partial: 'survey_graphs', locals: { div_name:  "chart_#{index}", graph_data: [['Jawapan','Bil'],['A',q.responses.where('answer = ?','A').count],['B',q.responses.where('answer = ?','B').count],['C',q.responses.where('answer = ?','C').count],['D',q.responses.where('answer = ?','D').count]], chart_title: "'Soalan #{index + 1}'", chart_type: chart_type}
                  
                  = content_tag('div','',id: "chart_#{index}")
              - when 'scale'
                %table.table.table-striped
                  %thead
                    %tr
                      %th
                        1
                      %th
                        2
                      %th
                        3
                      %th
                        4
                      %th
                        5
                  %tbody
                    %tr
                      %td
                        = q.responses.where('answer = ?','1').count
                      %td
                        = q.responses.where('answer = ?','2').count
                      %td
                        = q.responses.where('answer = ?','3').count
                      %td
                        = q.responses.where('answer = ?','4').count
                      %td
                        = q.responses.where('answer = ?','5').count
                %div
                  = render partial: 'survey_graphs', locals: { div_name:  "chart_#{index}", graph_data: [['Jawapan','Bil'],['1',q.responses.where('answer = ?','1').count],['2',q.responses.where('answer = ?','2').count],['3',q.responses.where('answer = ?','3').count],['4',q.responses.where('answer = ?','4').count],['5',q.responses.where('answer = ?','5').count]], chart_title: "'Soalan #{index + 1}'", chart_type: chart_type}

                  = content_tag('div','',id: "chart_#{index}")

              - when 'subjective'
                %table.table.table-striped
                  %thead
                    %tr
                      %th
                        = t('answers')
                  %tbody
                    - q.responses.each do |a|
                      %tr
                        %td
                          = a.answer

app/views/surveys/show.html.haml
- model_class = Survey
.row
  %h3.twelve.columns
    = @survey.title
  %hr.divider
.row
  .twelve.columns
    %strong= t('.name')
    %h5
      = @survey.title
.row
  .twelve.columns
    %strong= t('description')
    %p= @survey.try(:description).try(:html_safe)

.row
  .twelve.columns
    = form_for @survey, url: survey_path do |f|
      - if @survey.sent?
        - if !@survey.completed
          = f.hidden_field :completed, value: 1
          %span.medium.pretty.btn.info
            = f.submit t('end_survey')
        %span.medium.pretty.btn.info
          = link_to t('report'), report_survey_path
      - unless @survey.sent?
        %span.medium.pretty.btn.warning
          = link_to t('edit', :default => t("helpers.links.edit")), edit_survey_path(@survey)
        %span.medium.pretty.btn.danger
          = link_to t('destroy', :default => t("helpers.links.destroy")), survey_path(@survey), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }
  %hr.divider
.row
  - unless @survey.sent?
    .twelve.columns
      %h5=t('send_survey_to')
      = form_for '',url: send_user_survey_path do |f|
        %ul
          - if current_user
            %li.field
              - if current_user.admin?
                .picker
                  = select_tag 'survey_user_select', options_for_select([[t('.all_users'),'all_users'],[t('.members'),'members'], [t('.nonmembers'),'nonmembers'],[t('.users_by_program'), 'users_by_program'],[t('.users_by_course'),'users_by_course']])
          - elsif current_consultant
            %li.field
              .picker
                = select_tag 'survey_user_select', options_for_select([[t('.users_by_program'), 'users_by_program'],[t('.users_by_course'),'users_by_course']])
          - if current_consultant
            %li.field.survey_program_select_field
              .picker
                = select_tag 'survey_program_select', options_for_select(current_consultant.programs.all.map{|a| [a.name, a.id]}), disabled: false
            %li.field.survey_course_select_field.hide
              .picker
                = select_tag 'survey_course_select', options_for_select(Course.where(program_id: current_consultant.programs.first.id).map{ |a| [a.name,a.id]}), disabled: true
          - else
            %li.field
              .picker
                = select_tag 'survey_program_select', options_for_select(Program.all.map{|a| [a.name, a.id]}), disabled: true, class: 'hide'
            %li.field
              .picker
                = select_tag 'survey_course_select', options_for_select(Course.where(program_id: Program.first.id).map{ |a| [a.name,a.id]}), disabled: true, class: 'hide'
          %li.field
            %span.medium.pretty.btn.info
              %button{:onClick => 'submit();'}
                = t('submit')
              /= f.submit t('submit')
  - else
    = t('this_survey_has_been_sent')

app/views/surveys/take.html.haml
.row
  %h3.twelve.columns
    = t '.title'
  %hr.divider
.row
  .twelve.columns
    = form_for '', :html => { :class => 'form-horizontal custom' } do |f|
      %ul
        - @questions.each do |q|
          = f.label q.title
          - the_field = ''
          - case q.question_type
            - when 'yes_no'
              %li.field
                .row
                  .three.columns
                    = radio_button "question[#{q.id}]", :answer, 'yes'
                    = f.label t('yes_answer')
                  .three.columns
                    = radio_button "question[#{q.id}]",:answer, 'no'
                    = f.label t('no_answer')
            - when 'multiple_choice'
              %li.field
                .row
                  .six.columns
                    = radio_button "question[#{q.id}]", :answer, 'A'
                    = f.label q.option1
                .row
                  .six.columns
                    = radio_button "question[#{q.id}]", :answer, 'B'
                    = f.label q.option2
                .row
                  .six.columns
                    = radio_button "question[#{q.id}]", :answer, 'C'
                    = f.label q.option3
                .row
                  .six.columns
                    = radio_button "question[#{q.id}]", :answer, 'D'
                    = f.label q.option4
            - when 'scale'
              %li.field
                .row
                  .three.columns
                    = f.label t('scale_low')
                  .four.columns
                  .three.columns
                    = f.label t('scale_high')
                .row
                  .two.columns
                    = radio_button "question[#{q.id}]", :answer, 1
                    1
                  .two.columns
                    = radio_button "question[#{q.id}]", :answer, 2
                    2
                  .two.columns
                    = radio_button "question[#{q.id}]", :answer, 3
                    3
                  .two.columns
                    = radio_button "question[#{q.id}]", :answer, 4
                    4
                  .two.columns
                    = radio_button "question[#{q.id}]", :answer, 5
                    5
            - when 'subjective'
              %li.field
                = text_area "question[#{q.id}]", :answer, class: 'textarea input', :rows => 8
          %li.field
            = hidden_field "question[#{q.id}]", 'question_id', value: q.id
        %li.field
          = f.submit t('submit'), :class => ' pretty medium warning btn normal'