config/routes.rb
BizPkns::Application.routes.draw do

  mount RedactorRails::Engine => '/redactor_rails'

  localized do
    get 'faq' => 'pages#faq', as: :faq
    get 'terms_and_conditions' => 'pages#terms_and_conditions', as: 'tnc'
    get "reports/users" => 'reports#users'
    get "reports/consultants" => 'reports#consultants'
    get "reports/programs" => 'reports#programs'
    get "reports/kpi" => 'reports#kpi'
    get "newsletters/history" => 'newsletters#history', as: "history"

    get "newsletters/new/:id" => 'newsletters#use_template', as: "use_template"
    get "home" => "pages#home"
    put 'make_member/:id' => 'users#make_member', as: :make_member
    match 'select_program/:program_id' => 'consultants#select_program', as: :select_program
    post 'update_attendance', to: 'members#update_attendance', as: 'update_attendance'
    get "newsletters/history" => 'newsletters#history', as: "history"
    get "newsletters/new/:id" => 'newsletters#use_template', as: "use_template"
    get "newsletters/preview/:id" => 'newsletters#preview', as: "preview_newsletter"
    get "letters/history" => 'letters#history', as: "letters_history"
    get "letters/list" => 'letters#list', as: "letters_list"
    get "letters/preview/:id" => 'letters#preview', as: "preview_letter"
    get "email/:id" => 'email#show', as: "show_email"
    match 'consultation' => "pages#consultation", as: :consultation
    match 'my_courses' => "pages#my_courses", as: :user_course_listing
    match 'program_users' => "members#program_member_list", as: :program_user_listing
    match "contact" => "pages#contact", as: :contact
    match 'create_message' => 'messages#create', as: :create_message
    get  '/upcoming_courses' => 'pages#upcoming_courses', as: :course_listing
    get 'blogs/tag/:tag', to: 'blogs#all', as: :tag
    match 'blog', to: 'blogs#all', as: :category_blog
    get 'blog/:id', to: 'blogs#show', as: :show_blog
    scope '/upcoming_courses' do 
       match '/:id' => 'pages#upcoming_courses_show', as: :course_details
       match '/:id/user/:user_id' => 'pages#register_user', as: :user_course_registration
    end

    match "/delayed_job" => DelayedJobWeb, :anchor => false
    match 'business_directory' => 'pages#business_directory', as: :business_directory
    get 'city_dropdown' => 'application#city_dropdown', as: :city_dropdown
    get 'course_dropdown' => 'application#course_dropdown', as: :course_dropdown
    devise_for :users, path_names: {sign_in: "login", sign_out: "logout", sign_up: "signup"},
                        controllers: {registrations: 'registrations', confirmations: 'confirmations', sessions: 'sessions'}
    devise_for :consultants, path_names: {sign_in: "login",  sign_out: "logout"}
    devise_scope :user do
      get "/admin/login" => "sessions#new_admin"
      post "/user/sign_in" => "sessions#create"
    end
    
    resources :reports, only: [] do
      collection do
        match 'users' => 'reports#users', as: :user
        match "consultants" => 'reports#consultants', as: :consultant
        match "programs" => 'reports#programs', as: :program
      end
    end
    resources :admin
    resources :adverts do
      member do 
        put 'activate' 
        put 'assign_weight'
        put 'make_request'
        post 'new'
        post 'edit'
      end
    end
    resources :consultants do
      member do
        match 'my_adverts', as: :my_adverts
        match 'my_reports', as: :my_reports
      end
    end
    resources :users do
      member do
        put 'update_membership' => 'users#update_membership'#, as: :update_membership
        get 'surveys'
        get 'letters', as: :letter_user
        match 'my_adverts', as: :my_adverts
      end 
      collection do
        get 'inactive' => 'users#inactive'
      end
    end
    resources :programs
    resources :courses do
      member do
        get 'generate_report'
        post 'create_report', as: :create_report
        get 'view_report'
        put 'update_report', as: :update_report
        get 'reports'
      end
      collection do 
        get 'list_reports'
      end
    end
    resources :members
    resources :educations
    resources :skills
    resources :blogs
    resources :attendance_list
    resources :pkns_users
    resources :businesses
    resources :email, :only => [:show]
    namespace :newsletters do resources :templates end
    resources :newsletters do
      member do
        post 'send_newsletter' => 'newsletters#send_newsletter', as: :send_user
      end
    end
    resources :past_attendances, except: [ :update, :destroy, :edit ] do
      collection do
        get 'uploaded'
      end
    end
    resources :business_categories
    resources :letters do
      collection do 
        get '' => 'letters#list'
      end
      member do
        post 'send_letter' => 'letters#send_letter', as: :send_user
        match 'generate_letter' => 'letters#generate_letter', as: :generate
      end
    end
    resources :surveys do
      member do
        post 'send_survey' => 'surveys#send_survey', as: :send_user
      end
      member do 
        get 'take'
        post 'take' => 'surveys#finish_survey'
        get 'report'
        post 'report'
      end
    end

    scope '/portal' do
      get '' => 'portals#home'
      get 'home' => 'portals#home', as: :portal_home
      get 'contact' => 'portals#contact', as: :portal_contact
      get 'course' => 'portals#course', as: :portal_course
      get 'faq' => 'portals#faq', as: :portal_faq
      get 'course/:id' => 'portals#course_show', as: :portal_course_show
      get 'members' => 'portals#member_page', as: :portal_members
    end
    get "pages/welcome", as: 'welcome_page'
    get "pages/adview", as: 'adview'
    get "consultants/:id/contact", :to => "consultants#contact", :as => 'contact_consultant'
    post "consultants/:id/contact/sent", :to => "consultants#sent", :as => 'contact_sent'
    get "letters/:id/compose", :to => "letters#compose", :as => 'compose_letter'
    put "admin/:id/update", :to => "admin#update", :as => "update_admin"

  end

  root :to => 'pages#welcome'

end

app/models/education.rb
class Education < ActiveRecord::Base
  attr_accessible :name

  has_many :educations_users, dependent: :destroy
  has_many :users, through: :educations_users

  validates_length_of :name, maximum: 140
end

app/controllers/educations_controller.rb
class EducationsController < ApplicationController
  # GET /educations
  # GET /educations.json
  def index
    @educations = Education.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @educations }
    end
  end

  # GET /educations/1
  # GET /educations/1.json
  def show
    @education = Education.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @education }
    end
  end

  # GET /educations/new
  # GET /educations/new.json
  def new
    @education = Education.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @education }
    end
  end

  # GET /educations/1/edit
  def edit
    @education = Education.find(params[:id])
  end

  # POST /educations
  # POST /educations.json
  def create
    @education = Education.new(params[:education])

    respond_to do |format|
      if @education.save
        format.html { redirect_to @education, notice: 'Education was successfully created.' }
        format.json { render json: @education, status: :created, location: @education }
      else
        format.html { render action: "new" }
        format.json { render json: @education.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /educations/1
  # PUT /educations/1.json
  def update
    @education = Education.find(params[:id])

    respond_to do |format|
      if @education.update_attributes(params[:education])
        format.html { redirect_to @education, notice: 'Education was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @education.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /educations/1
  # DELETE /educations/1.json
  def destroy
    @education = Education.find(params[:id])
    @education.destroy

    respond_to do |format|
      format.html { redirect_to educations_url }
      format.json { head :no_content }
    end
  end
end

app/views/educations/_form.html.haml
= form_for @education, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label t('.name'), :class => 'control-label'
    .controls
      = f.text_field :name, :class => 'text_field'
 
  .form-actions
    %span.medium.pretty.btn.primary
      = f.submit t('.new')#, :class => 'btn btn-primary'

app/views/educations/edit.html.haml
- model_class = Education
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/educations/index.html.haml
- model_class = Education

.row
  %h3.ten.columns
    = t('.title', :default => model_class.model_name.human.pluralize)
  .two.columns.action
    %span.pretty.medium.primary.btn.entypo.icon-left.icon-list-add
      = link_to t('new', :default => t("helpers.links.new")), new_education_path
.table
  .row.table-head
    .two.columns
      %h6.title= "Bil"
    .eight.columns
      %h6.title= t('.name')
    .two.columns
      %h6.title= t('status')
  - @educations.each_with_index do |education, i|
    .row.table-rows
      .two.columns
        %p
          = i + 1
      .eight.columns
        %p
          = education.name
      .two.columns
        .row
          .twelve.columns
          .twelve.columns
            %span.pretty.small.btn.info.icon-left.entypo.icon-list-add
              = link_to t('edit', :default => t("helpers.links.edit")), edit_education_path(education)
          .twelve.columns
            %span.pretty.small.btn.danger.icon-left.entypo.icon-trash
              = link_to t('destroy', :default => t("helpers.links.destroy")),education_path(education),
                :method => :delete,
                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }

app/views/educations/new.html.erb
<%- model_class = Education -%>
<div class="page-header">
  <h1><%=t '.title' %></h1>
</div>
<%= render :partial => 'form' %>

app/views/educations/new.html.haml
%h1 New education

= render 'form'

= link_to 'Back', educations_path

app/views/educations/show.html.haml
- model_class = Education
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= t(".name") + ':'
  = @education.name

.form-actions
  %span.medium.pretty.btn.secondary
    = link_to t('.edit', :default => t("helpers.links.edit")), edit_education_path(@education)#, :class => 'btn'
  %span.medium.pretty.btn.danger
    = link_to t('.destroy', :default => t("helpers.links.destroy")), education_path(@education), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }#, :class => 'btn btn-danger'
  %span.medium.pretty.btn.warning
    = link_to t('back'), educations_path